### ISSUE TITLE
Arduino compatible?

### ISSUE THREAD

**Issue by torehc** [Screetsec/Brutal#1]
Hi, very good project to mix learning in software and hardware. Congratulations!

I wanted to ask you if you have thought about extending the hardware to the Arduino, specifically the Arduino nano, micro or leonardo. So I think it would be more public to have this hardware more people and also be more economical.

Regards!

**Comment by waidakyaw** [comment]
Hi....Very Perfect Project......For Usefull Linux User....
Thank you Very Much ,.....

**Comment by fguisso** [comment]
What about Arduino Uno?

Perfect Project, congrats!
