### ISSUE TITLE
arduino Leonardo ATMEGA32U4 USB

### ISSUE THREAD

**Issue by markyy1991** [Screetsec/Brutal#10]
Works with this chip?

arduino Leonardo ATMEGA32U4 USB

**Comment by myugan** [comment]
sorry, lib and source is different. stay tune xD

**Comment by raioramalho** [comment]
See my application https://github.com/RamalhoSec/InserKey-tool @markyy1991

**Comment by markyy1991** [comment]
What its this?


________________________________
De: Alan Ramalho <notifications@github.com>
Enviado: sábado, 25 de agosto de 2018 16:13
Para: Screetsec/Brutal
Cc: markyy1991; Mention
Asunto: Re: [Screetsec/Brutal] arduino Leonardo ATMEGA32U4 USB (#10)


See my application https://github.com/RamalhoSec/InserKey-tool @markyy1991<https://github.com/markyy1991>

[https://avatars0.githubusercontent.com/u/13089323?s=400&v=4]<https://github.com/RamalhoSec/InserKey-tool>

GitHub - RamalhoSec/InserKey-tool: Tool for gennerate ...<https://github.com/RamalhoSec/InserKey-tool>
github.com
Tool for gennerate Scripts for Arduino leonardo Using teeOnArdu lib like a RubberDucky From hak5
